name: Build ARM64 Debian Package

on:
  push:
   branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Git tag version
        id: get_version
        run: |
          VERSION=0.0.0-$(git rev-parse --short HEAD)
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU for ARM64
        uses: docker/setup-qemu-action@v2

      - name: Build Debian package inside ARM64 container
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          # docker run --rm -v $(pwd):/workspace -w /workspace ghcr.io/${{ github.repository }}:latest \
          docker run --platform=linux/arm64/v8 --rm -v $(pwd):/workspace -w /workspace nabaco/gstreamer-dev \
            /bin/bash -c "
            export VERSION=$VERSION &&
            ./autogen.sh &&
            ./configure --host=aarch64-linux-gnu &&
            make &&
            checkinstall -D -y --pkgname=remote-audio \
              --arch=arm64 \
              --install=no \
              --pkgversion=$VERSION \
              --pkggroup=audio \
              --requires=\"network-manager,inadyn\"
          "

      - name: Upload Debian package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: remote-audio_${{ steps.get_version.outputs.version }}-1_arm64.deb
          path: remote-audio_${{ steps.get_version.outputs.version }}-1_arm64.deb
