name: Build ARM64 Debian Package

on:
  push:
    tags:
      - 'v*' # Trigger on Git tags like v1.0.0

jobs:
  build-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Git tag version
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU for ARM64
        uses: docker/setup-qemu-action@v2

      - name: Build Debian package inside ARM64 container
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          # docker run --rm -v $(pwd):/workspace -w /workspace ghcr.io/${{ github.repository }}:latest \
          docker run --platform=linux/arm64/v8 --rm -v $(pwd):/workspace -w /workspace nabaco/gstreamer-dev \
            /bin/bash -c "
            export VERSION=$VERSION &&
            ./autogen.sh &&
            ./configure --host=aarch64-linux-gnu &&
            make &&
            checkinstall -D -y --pkgname=remote-audio --pkgversion=$VERSION --arch=arm64 --pkggroup=audio --install=no
          "

      - name: Create release and upload Debian artifact
        uses: softprops/action-gh-release@v2
        with:
          files: remote-audio_${{ steps.get_version.outputs.version }}-1_arm64.deb
